### ISSUE TITLE
How to use it in IOT Manager Android App ?

### ISSUE THREAD

**Issue by xerosanyam** [4refr0nt/iotmanager-heroku#1]
Hey, can you please explain how can one use the heroku demo in the IOT Manager Android App.
Thanks

**Comment by 4refr0nt** [comment]
Its demo device lunched on https://iotmanager-demo.herokuapp.com/

**Comment by xerosanyam** [comment]
Yes. I understand that, but how to configure the android app to pick data from the herokuapp ??

**Comment by 4refr0nt** [comment]
U can use this settings https://github.com/4refr0nt/iotmanager-heroku/blob/master/config.js#L14
