### ISSUE TITLE
new color not accept

### ISSUE THREAD

**Issue by iranweld** [4refr0nt/iotmanager-heroku#3]
Hi 
I want add new item in Air conditioning , item added in software 
butt new color not show in App.

String setAirStatus(String air) {

    String  airStatus;
    
    if (air == "0") {       
     airStatus = "{\"status\":" + air +",\"color\":\"yellow\"}";
        
    } else if (air == "1") {
     airStatus = "{\"status\":" + air +",\"color\":\"blue\"}";
        
    } else if (air == "2") {
      airStatus = "{\"status\":" + air +",\"color\":\"green\"}";
        
    }
    else if (air == "3") {
      airStatus = "{\"status\":" + air +",\"color\":\"red\"}";
        
    }

    return airStatus;
}

![WhatsApp Image 2020-01-25 at 09 41 17](https://user-images.githubusercontent.com/4194016/73117201-34471600-3f57-11ea-9e2f-7c2b28db97b2.jpg)

**Comment by 4refr0nt** [comment]
Hi!
You can use `orange`, `yellow` not yet supported, sorry for this.
